#!/usr/bin/env bash
# pin_os.sh — open the bake-pin PR on ha-operating-system for a released
# greenautarky-site version.
#
# Usage: scripts/ci/pin_os.sh <version> [--draft]
# Needs: GH_TOKEN with contents:write + pull-requests:write on
#        greenautarky/ha-operating-system. Run from the repo root.
#
# Why this exists: a release published to GHCR reaches no device until
# ha-operating-system/version.yaml pins it, and that pin was done by hand —
# so a release could sit finished and unpinned with nothing saying so. An
# open PR is visible; a forgotten manual step is not.
#
# Idempotent: exits 0 without a PR when version.yaml already pins <version>.
# Fails (exit 1) when it cannot find the pin line — never guesses.
set -euo pipefail

VER="${1:?usage: pin_os.sh <version> [--draft]}"
DRAFT="${2:-}"
OS_REPO="${OS_REPO:-greenautarky/ha-operating-system}"
KEY="greenautarky-site"
: "${GH_TOKEN:?GH_TOKEN is not set}"

[[ "$VER" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]] \
  || { echo "::error::'$VER' is not a version"; exit 1; }

# One-line summary for the version.yaml comment: the first bold sentence
# under this version's CHANGELOG heading, read from the release tag
# (falls back to the checked-out CHANGELOG when the tag is not local). Optional — the PR is still right
# without it, so a missing entry degrades to a pointer, loudly.
SUMMARY=$(awk -v v="## $VER" '
  $0==v || index($0, v" ")==1 {f=1; next}
  f && /^## / {exit}
  f && match($0, /\*\*[^*]+\*\*/) {print substr($0, RSTART+2, RLENGTH-4); exit}
' < <(git show "v${VER}:CHANGELOG.md" 2>/dev/null || cat CHANGELOG.md) || true)
if [ -z "$SUMMARY" ]; then
  echo "::warning::no '## $VER' entry with a bold headline in CHANGELOG.md — the pin comment will only point at the changelog"
  SUMMARY="see greenautarky-onboarding CHANGELOG"
fi
SUMMARY=${SUMMARY//\"/\'}

work=$(mktemp -d -p "${RUNNER_TEMP:-${TMPDIR:-/tmp}}")
trap 'rm -rf "$work"' EXIT
# The token reaches git through a credential helper that reads the env at
# run time — never in a URL or argv, where the process table shows it.
export GIT_TERMINAL_PROMPT=0
CRED='!f() { echo username=x-access-token; echo "password=${GH_TOKEN}"; }; f'
git -c credential.helper= -c credential.helper="$CRED" \
  clone -q --depth 1 "https://github.com/${OS_REPO}.git" "$work/os"
cd "$work/os"
git config credential.helper ""
git config --add credential.helper "$CRED"

line=$(grep -nE "^  ${KEY}:[[:space:]]*\"[^\"]+\"" version.yaml || true)
[ "$(printf '%s\n' "$line" | grep -c .)" = 1 ] \
  || { echo "::error::expected exactly one '  ${KEY}: \"x.y.z\"' line in ${OS_REPO}/version.yaml, found: '${line}'"; exit 1; }
cur=$(printf '%s\n' "$line" | sed -E 's/^[0-9]+:  [^"]*"([^"]+)".*/\1/')

if [ "$cur" = "$VER" ]; then
  echo "${OS_REPO} already pins ${KEY} ${VER} — no PR needed"
  exit 0
fi

today=$(TZ=Europe/Berlin date +%F)
new="  ${KEY}: \"${VER}\"  # ${VER} (${today}): ${SUMMARY}. PREVIOUS ${cur}."
NEW="$new" KEY="$KEY" python3 - <<'EOF'
import os, re
p = "version.yaml"
s = open(p).read()
pat = re.compile(r'^  ' + re.escape(os.environ["KEY"]) + r':[ \t]*"[^"]+".*$', re.M)
s2, n = pat.subn(lambda _: os.environ["NEW"], s)
assert n == 1, n
open(p, "w").write(s2)
EOF
git diff --stat
[ "$(git diff --numstat | awk '{print $1+$2}')" = 2 ] \
  || { echo "::error::the edit touched more than the one pin line"; exit 1; }

br="ci/pin-${KEY}-${VER}"
git config user.name "ga-ci-bot"
git config user.email "ci@greenautarky.com"
git checkout -q -b "$br"
git commit -qam "chore(bake): pin ${KEY} ${VER} (auto from greenautarky-onboarding release)"
git push -q -f origin "$br"

body="Auto-generated by greenautarky-onboarding after publishing \`${KEY} ${VER}\` to GHCR (was \`${cur}\`).

Changelog: https://github.com/greenautarky/greenautarky-onboarding/blob/v${VER}/CHANGELOG.md

This PR only moves the pin. The version reaches devices with the next bake (rc) that includes it, and a bake is still started by hand."

if gh pr view "$br" --repo "$OS_REPO" --json state -q .state 2>/dev/null | grep -qx OPEN; then
  echo "PR for $br already open — branch updated"
else
  args=(--repo "$OS_REPO" --base master --head "$br"
        --title "chore(bake): pin ${KEY} ${VER}" --body "$body")
  [ "$DRAFT" = "--draft" ] && args+=(--draft)
  gh pr create "${args[@]}" >/dev/null
fi
url=$(gh pr view "$br" --repo "$OS_REPO" --json url -q .url)
test -n "$url" || { echo "::error::could not create or find the pin PR"; exit 1; }
echo "pin PR -> $url"
[ -n "${GITHUB_STEP_SUMMARY:-}" ] && echo "Pin PR: $url" >> "$GITHUB_STEP_SUMMARY"
exit 0
